### ISSUE TITLE
Image download link is obsolete in lesson 1/4

### ISSUE THREAD

**Issue by romanchelsea** [GameHackingAcademy/vmsetup#2]
Hi there,

Thanks for providing this nice tutorial.

The windows image link on this [page ](https://gamehacking.academy/lesson/1/4)seems obsolete.

> The Microsoft Edge team no longer offers VM image downloads for the testing of Microsoft Edge and Internet Explorer.

You may consider updating the link to https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

-Xiongwei

**Comment by attilathedud** [comment]
Thanks for that catch! I'll adjust the link soon.

**Comment by attilathedud** [comment]
Fell off the radar, but the links have been fixed.
