### ISSUE TITLE
x32dbg version causes crash on breakpoint

### ISSUE THREAD

**Issue by harimadhavan2000** [GameHackingAcademy/vmsetup#3]
hello, much gratitude for this course.
a small issue - when i try to apply a breakpoint using x32dbg, as in https://gamehacking.academy/lesson/2/4, and the execution reaches it; my VM crashes totally?
is this a problem with the x32dbg version included?
thanks!

**Comment by attilathedud** [comment]
Interesting, I've never run into this issue. Does it crash when you attach to other processes as well? Also, how much RAM do you have available for your VM?
